apiVersion: v1
kind: Service
metadata:
  name: simple-calculator-service
spec:
  type: NodePort
  selector:
    app: simple-calculator
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080